
package com.example.lab2.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerController", targetNamespace = "http://lab2.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerController {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://lab2.example.com/", className = "com.example.lab2.webservice.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://lab2.example.com/", className = "com.example.lab2.webservice.GetNameResponse")
    @Action(input = "http://lab2.example.com/ServerController/getNameRequest", output = "http://lab2.example.com/ServerController/getNameResponse")
    public String getName();

    /**
     * 
     * @return
     *     returns com.example.lab2.webservice.ServerMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getState", targetNamespace = "http://lab2.example.com/", className = "com.example.lab2.webservice.GetState")
    @ResponseWrapper(localName = "getStateResponse", targetNamespace = "http://lab2.example.com/", className = "com.example.lab2.webservice.GetStateResponse")
    @Action(input = "http://lab2.example.com/ServerController/getStateRequest", output = "http://lab2.example.com/ServerController/getStateResponse")
    public ServerMessage getState();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "doTurn", targetNamespace = "http://lab2.example.com/", className = "com.example.lab2.webservice.DoTurn")
    @ResponseWrapper(localName = "doTurnResponse", targetNamespace = "http://lab2.example.com/", className = "com.example.lab2.webservice.DoTurnResponse")
    @Action(input = "http://lab2.example.com/ServerController/doTurnRequest", output = "http://lab2.example.com/ServerController/doTurnResponse")
    public void doTurn(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
